import type { Metadata } from "next";
import { Poppins } from "next/font/google";

// ignore error for css import
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
import "@/app/globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dark">
      <body className={`${poppins.variable} antialiased bg-base-100`}>
        {children}
      </body>
    </html>
  );
}
